// Frozen copies of every Hinglish (Latin-script) reminder wording this app has shipped. A stored
// template that still matches one of these exactly was never edited by the driver, so it can safely be
// upgraded to the Hindi (Devanagari) version. Anything else is the driver's own text and is left alone.
export const LEGACY_HINGLISH_CURRENT = {
  "advance": "Namaste {parent_name} ji 🙏\n\n{student_name} ({class}) ki cab fee ka ek chhota sa reminder.\n\nPeriod   : {period}\nAmount   : *Rs. {amount}*\nDue date : *{due_date}*\nPickup   : {pickup_point}\n\nKripya due date tak payment kar dijiyega.\n{qr_note}\nUPI ID: {upi_id}\nMobile number: {operator_phone}\nPayment link: {pay_link}\n\nPayment hone par receipt bhej diya jayega. Agar payment ho chuka hai to please bata dijiye.\n\nDhanyavaad 🙏\n{operator_name}\n{operator_phone}",
  "due": "Namaste {parent_name} ji 🙏\n\n{student_name} ({class}) ki cab fee *aaj due* hai.\n\nPeriod : {period}\nAmount : *Rs. {amount}*\n\nKripya aaj hi payment kar dijiye.\n{qr_note}\nUPI ID: {upi_id}\nMobile number: {operator_phone}\nPayment link: {pay_link}\n\nAgar payment ho chuka hai to please mujhe bata dijiye, main record update kar lunga.\n\nDhanyavaad 🙏\n{operator_name}\n{operator_phone}",
  "overdue": "Namaste {parent_name} ji 🙏\n\n{student_name} ({class}) ki cab fee *{days_overdue} din* se pending hai.\n\nPeriod   : {period}\nAmount   : *Rs. {amount}*\nDue date : {due_date}\n\nKripya jaldi payment kar dijiye.\n{qr_note}\nUPI ID: {upi_id}\nMobile number: {operator_phone}\nPayment link: {pay_link}\n\nAgar aap payment kar chuke hain to screenshot bhej dijiye, main record theek kar dunga. Koi dikkat ho to mujhe call kar lijiye, hum baat karke hal nikal lenge.\n\nDhanyavaad 🙏\n{operator_name}\n{operator_phone}",
  "final": "Namaste {parent_name} ji,\n\n{student_name} ({class}) ki cab fee *{days_overdue} din* se pending hai. Pehle bhi reminder bheja tha.\n\nAmount   : *Rs. {amount}*\nDue date : {due_date}\n\nPayment clear na hone par mujhe cab service temporarily rokni pad sakti hai, jo hum nahi chahte. Kripya aaj hi payment kar dijiye ya mujhe call karke bata dijiye.\n{qr_note}\nUPI ID: {upi_id}\nMobile number: {operator_phone}\nPayment link: {pay_link}\n\nAgar payment ho chuka hai to please mujhe turant bata dijiye.\n\nDhanyavaad 🙏\n{operator_name}\n{operator_phone}",
  "receipt": "Namaste {parent_name} ji 🙏\n\nAapka payment mil gaya hai. Bahut dhanyavaad.\n\nReceipt : {receipt_no}\nStudent : {student_name} ({class})\nPeriod  : {period}\nAmount  : *Rs. {amount}*\nMode    : {mode}\nDate    : {paid_on}\n\n{operator_name}\n{operator_phone}"
};

export const LEGACY_HINGLISH_FIRST_RELEASE = {
  "advance": "Namaste {parent_name} ji,\n\n{student_name} ({class}) ki cab fee ki due date *{due_date}* hai.\n\nPeriod : {period}\nAmount : *Rs. {amount}*\nPickup : {pickup_point}\n\nTime par payment kar dijiyega. Dhanyavaad.\n\n{operator_name}\n{operator_phone}",
  "due": "Namaste {parent_name} ji,\n\n{student_name} ({class}) ki cab fee *aaj due* hai.\n\nPeriod : {period}\nAmount : *Rs. {amount}*\n\nAaj hi payment kar dijiye to badi meherbani hogi.\n\n{operator_name}\n{operator_phone}",
  "overdue": "Namaste {parent_name} ji,\n\n{student_name} ({class}) ki cab fee *{days_overdue} din* se pending hai.\n\nPeriod : {period}\nAmount : *Rs. {amount}*\nDue    : {due_date}\n\nKripya jaldi clear kar dijiye. Koi problem ho to mujhe call kar lijiye.\n\n{operator_name}\n{operator_phone}",
  "final": "Namaste {parent_name} ji,\n\n{student_name} ki cab fee *{days_overdue} din* se pending hai.\n\nAmount : *Rs. {amount}*\nDue    : {due_date}\n\nPayment clear na hone par cab service temporarily rokni pad sakti hai. Kripya aaj hi baat kar lijiye.\n\n{operator_name}\n{operator_phone}",
  "receipt": "Namaste {parent_name} ji,\n\nPayment mil gaya hai. Dhanyavaad.\n\nReceipt : {receipt_no}\nStudent : {student_name} ({class})\nPeriod  : {period}\nAmount  : *Rs. {amount}*\nMode    : {mode}\nDate    : {paid_on}\n\n{operator_name}"
};
