// All interface labels in Hindi (Devanagari) and English, switchable from the top bar and Settings.
// Placeholders in braces, like {name}, are filled in by the screen that uses the text.
export const strings = {
  hi: {
    appName: 'Cab Fee Reminder',
    offline: 'ऑफ़लाइन · सारा डेटा फ़ोन में',
    lock: 'लॉक',
    lockHint: 'अपना MPIN डालिए। बच्चों का डेटा सिर्फ़ इसी फ़ोन में रहता है।',
    lockFoot: 'MPIN भूल गए? बैकअप फ़ाइल से डेटा वापस आता है — कोई सर्वर नहीं है। 10 बार गलत डालने पर 60 सेकंड रुकना पड़ेगा।',
    setupTitle: 'शुरू करते हैं',
    setupHint: 'पहले अपनी जानकारी दीजिए और 4 अंकों का MPIN चुनिए। ऐप खोलने पर हर बार यही MPIN पूछा जाएगा।',
    yourName: 'आपका नाम',
    businessName: 'कैब सर्विस का नाम (ज़रूरी नहीं)',
    yourPhone: 'आपका मोबाइल नंबर',
    setMpin: 'MPIN चुनिए (4 अंक)',
    confirmMpin: 'MPIN दोबारा डालिए',
    mpinMismatch: 'दोनों MPIN एक जैसे नहीं हैं।',
    wrongMpin: 'MPIN गलत है।',
    finishSetup: 'शुरू कीजिए',
    dashboard: 'आज का हिसाब',
    remindersPending: 'भेजने हैं रिमाइंडर',
    tapToSend: 'दबाकर भेजिए',
    outstanding: 'बाकी पैसा',
    overduePart: 'लेट',
    collected: 'मिला',
    thisMonth: 'इस महीने',
    activeStudents: 'चालू बच्चे',
    dueThisWeek: 'इस हफ़्ते देय',
    generateInvoices: 'नए बिल जाँचिए',
    invoicesCreated: '{n} नए बिल बन गए।',
    upToDate: 'सब कुछ पहले से अप-टू-डेट है।',
    backupStatus: 'बैकअप',
    backupNagAmber: 'दिन से बैकअप नहीं हुआ। कर लीजिए।',
    backupNagRed: 'दिन से बैकअप नहीं हुआ! अभी कर लीजिए।',
    backupNagFirst: 'अभी तक बैकअप नहीं हुआ।',
    queue: 'रिमाइंडर',
    sendAll: 'सब भेजिए',
    send: 'भेजिए',
    skip: 'छोड़िए',
    undo: 'वापस लीजिए',
    amount: 'रकम',
    sendingTo: 'किसको',
    messagePreview: 'मैसेज',
    openWhatsApp: 'WhatsApp खोलिए',
    queueEmptyTitle: 'सारे रिमाइंडर हो गए।',
    queueEmptyBody: 'अभी कोई रिमाइंडर बाकी नहीं है।',
    backToDash: 'होम पर वापस',
    sentToday: 'आज भेजे गए',
    nPending: '{n} बाकी',
    quietHoursNote: 'शांत समय चल रहा है (रात 8 से सुबह 8) — रिमाइंडर सुबह दिखेंगे।',
    students: 'बच्चे',
    searchPlaceholder: 'नाम, स्कूल या नंबर से खोजिए',
    noResults: 'कुछ नहीं मिला।',
    addStudent: 'नया बच्चा जोड़िए',
    all: 'सब',
    overdue: 'लेट',
    pending: 'बाकी',
    paid: 'हो गया',
    safetyCard: 'सुरक्षा कार्ड',
    bloodGroup: 'ब्लड ग्रुप',
    bloodUnknown: 'पता नहीं',
    allergies: 'एलर्जी',
    emergency: 'इमरजेंसी',
    father: 'पापा',
    mother: 'मम्मी',
    call: 'कॉल',
    record: 'जानकारी',
    ledger: 'हिसाब',
    notes: 'नोट्स',
    edit: 'बदलिए',
    enrolment: 'फ़ीस सेटअप',
    recordPayment: 'पेमेंट लिखिए',
    share: 'शेयर',
    studentName: 'बच्चे का नाम',
    classLabel: 'कक्षा',
    school: 'स्कूल',
    fatherName: 'पापा का नाम',
    fatherPhone: 'पापा का नंबर',
    motherName: 'मम्मी का नाम',
    motherPhone: 'मम्मी का नंबर',
    emergencyNumber: 'इमरजेंसी नंबर',
    pickupPoint: 'पिकअप पॉइंट',
    allergyPlaceholder: 'जैसे: मूँगफली, धूल — इनहेलर बैग में',
    cancel: 'रहने दीजिए',
    saveStudent: 'सेव कीजिए',
    pickups: 'पिकअप पॉइंट',
    pickupIntro: 'किराया यहीं से आता है। जिस पॉइंट पर बच्चे हैं वह हटेगा नहीं — सिर्फ़ बंद हो सकता है।',
    perMonth: 'प्रति माह',
    addPickup: 'नया पिकअप पॉइंट',
    fareLockNote: 'किराया बदलने से पुराने बिल नहीं बदलते — फ़ीस सेट करते समय किराया लॉक हो जाता है।',
    student: 'बच्चा',
    feePlan: 'फ़ीस प्लान',
    planMonthly: 'महीना',
    planQuarterly: 'तीन महीने',
    planYearly: 'साल',
    monthShort: 'माह',
    farePreview: 'कितना बनेगा',
    lockedFare: 'लॉक किया किराया',
    dueDay: 'देय तारीख़',
    firstInvoice: 'पहला बिल',
    lockExplain: 'यह किराया फ़ीस सेट के साथ लॉक हो जाएगा। बाद में पॉइंट का किराया बदल भी जाए, तो इस परिवार का पुराना हिसाब वैसा ही रहेगा।',
    saveEnrolment: 'फ़ीस सेव कीजिए',
    fareLockedToast: 'किराया {fare} पर लॉक ✓',
    invoices: 'बिल',
    outstandingTab: 'बाकी',
    overdueTab: 'लेट',
    paidTab: 'हो गया',
    payment: 'पेमेंट',
    settling: 'किस बिल का',
    amountReceived: 'कितना मिला',
    mode: 'कैसे मिला',
    modeCash: 'नकद',
    modeUPI: 'UPI',
    modeBank: 'बैंक ट्रांसफ़र',
    modeCheque: 'चेक',
    modeOther: 'अन्य',
    reference: 'रेफ़रेंस',
    refPlaceholder: 'UPI रेफ़रेंस या चेक नंबर',
    paidOn: 'तारीख़',
    receiptNo: 'रसीद',
    receiptLabel: 'रसीद',
    savePayment: 'पेमेंट सेव कीजिए',
    paymentSaved: 'पेमेंट लिख लिया',
    invoiceSettled: 'बिल पूरा हो गया और लिस्ट से हट गया।',
    balanceRemaining: 'बाकी रकम: {amount}',
    partPaymentNote: 'आंशिक पेमेंट — बाकी {amount} लिस्ट में रहेगा।',
    fullAmountNote: 'पूरी रकम — बिल पूरा हो जाएगा।',
    dueOn: 'देय {date}',
    receiptPreview: 'रसीद',
    shareReceipt: 'रसीद WhatsApp पर भेजिए',
    done: 'हो गया',
    templates: 'मैसेज',
    placeholders: 'प्लेसहोल्डर — दबाकर डालिए',
    livePreview: 'ऐसा दिखेगा',
    unknownPlaceholder: 'यह प्लेसहोल्डर पहचाना नहीं गया: {p} — सेव नहीं होगा।',
    saved: 'सेव हो गया ✓',
    backup: 'बैकअप',
    lastBackup: 'पिछला बैकअप',
    backupNow: 'अभी बैकअप कीजिए',
    backupNever: 'कभी नहीं',
    backupToday: 'आज',
    backupDaysAgo: '{n} दिन पहले',
    backupExplain: 'बैकअप एक फ़ाइल होती है। उसे Google Drive, ईमेल या अपने ही WhatsApp पर भेज दीजिए। फ़ोन खो गया तो सिर्फ़ यही फ़ाइल आपका डेटा बचाएगी।',
    restore: 'रिस्टोर',
    restoreExplain: 'पुरानी बैकअप फ़ाइल से सारा डेटा वापस आ जाएगा।',
    restoreTitle: 'यह बैकअप वापस लाएँ?',
    restoreBody: 'अभी: {cs} बच्चे, {ci} बिल।\nफ़ाइल में: {ns} बच्चे, {ni} बिल।\n\nफ़ोन का अभी का सारा डेटा इस फ़ाइल से बदल जाएगा। यह वापस नहीं होगा।',
    yesRestore: 'हाँ, वापस लाइए',
    restored: 'वापस आ गया ✓',
    chooseFile: 'फ़ाइल चुनिए',
    reports: 'रिपोर्ट',
    billed: 'बिल बना',
    collectionRate: 'वसूल हो गया',
    byPickupPoint: 'पिकअप पॉइंट के हिसाब से',
    point: 'पॉइंट',
    due: 'बाकी',
    defaulters: '30 दिन से ज़्यादा पुराना बाकी',
    noneRightNow: 'अभी कोई नहीं।',
    exportCsv: 'CSV एक्सपोर्ट कीजिए',
    csvExported: 'CSV बन गई ✓',
    settings: 'सेटिंग',
    languageSection: 'भाषा / Language',
    operatorProfile: 'आपकी जानकारी',
    billing: 'बिलिंग',
    defaultDueDay: 'हर महीने देय तारीख़',
    escalation: 'रिमाइंडर कब जाएँ',
    quietHours: 'रात में बंद',
    quietNote: 'सिर्फ़ सुबह 8 से रात 8 बजे तक',
    security: 'सुरक्षा',
    lockNow: 'अभी लॉक कीजिए',
    mpinNote: 'ऐप 5 मिनट बैकग्राउंड में रहे तो MPIN दोबारा पूछा जाएगा।',
    more: 'और',
    home: 'होम',
    money: 'पैसा',
    paymentDetails: 'पेमेंट की जानकारी',
    upiId: 'आपका UPI ID',
    upiHelp: 'मैसेज में "पेमेंट लिंक" और UPI ID जाएगा। लिंक खोलने पर माता-पिता को रकम, UPI ID कॉपी करने का बटन और QR दिखेगा। खाली छोड़ने पर ये लाइनें नहीं जाएँगी।',
    upiInvalid: 'UPI ID सही नहीं लग रहा (जैसे naam@bank)। सेव नहीं हुआ।',
    testPayLink: 'पेमेंट लिंक जाँचिए (₹1)',
    paymentQr: 'पेमेंट QR',
    uploadQr: 'QR की फोटो चुनिए',
    changeQr: 'QR बदलिए',
    qrSaved: 'QR सेव हो गया ✓',
    attachQr: 'हर रिमाइंडर के साथ QR भेजिए',
    qrHelp: 'ज़रूरी नहीं। पेमेंट लिंक काफ़ी है। QR चालू करने पर WhatsApp की "शेयर" लिस्ट खुलेगी और अभिभावक की चैट आपको खुद चुननी होगी, इसलिए यह धीमा है।',
    qrPickChat: 'WhatsApp में अभिभावक की चैट चुनिए',
    reminderTo: 'रिमाइंडर किसको भेजना है',
    reminderToHelp: 'एक अभिभावक चुनने पर आधे बटन दबाने पड़ेंगे। उनका नंबर न हो तो दूसरे को जाएगा।',
    both: 'दोनों',
    feeDetails: 'फ़ीस की जानकारी',
    billFrom: 'बिलिंग कब से',
    startToday: 'आज से',
    startMonth: 'इस महीने की 1 से',
    startNext: 'अगले महीने से',
    thisMonthFee: 'इस महीने की फ़ीस',
    unpaid: 'बाकी है',
    alreadyPaid: 'दे दी है',
    oldDues: 'पुराना बाकी (₹)',
    oldDuesHelp: 'पिछले महीनों का जितना पैसा बाकी हो। नहीं है तो खाली छोड़िए।',
    saveAndNext: 'सेव करके अगला जोड़िए',
    moreDetails: 'और जानकारी (बाद में भी भर सकते हैं)',
    quickHint: 'सिर्फ़ नाम, कक्षा, पिकअप पॉइंट और एक अभिभावक का नंबर ज़रूरी है।',
    addPickupFirst: 'पहले एक पिकअप पॉइंट जोड़िए (और → पिकअप पॉइंट)।',
    importStudents: 'Excel/CSV से जोड़िए',
    importIntro: 'Excel या Google Sheet की पूरी लिस्ट एक साथ डालिए। पहली लाइन में कॉलम के नाम होने चाहिए।',
    chooseCsv: 'CSV फ़ाइल चुनिए',
    orPaste: 'या शीट से कॉपी करके यहाँ पेस्ट कीजिए',
    downloadTemplate: 'नमूना फ़ाइल डाउनलोड कीजिए',
    checkFile: 'जाँचिए',
    importNow: 'अभी जोड़िए',
    importDone: 'बच्चे जुड़ गए',
    readyToAdd: '{n} जोड़ने के लिए तैयार',
    alreadyInApp: '{n} पहले से ऐप में हैं (छोड़ दिए)',
    haveProblems: '{n} में गड़बड़ी है (छोड़ दिए)',
    missingColumns: 'ये कॉलम नहीं मिले:',
    ignoredColumns: 'ये कॉलम छोड़ दिए गए:',
    newPickupsCreated: 'ये नए पिकअप पॉइंट बनेंगे:',
    andMore: '…और {n}।',
    rowN: 'लाइन {n}',
    sendReminderNow: 'रिमाइंडर अभी भेजिए',
    sendReminderNowHelp: 'देय तारीख़ का इंतज़ार किए बिना, आज के हिसाब का मैसेज।',
    lockedWait: 'MPIN बहुत बार गलत डाला। रुककर फिर कोशिश कीजिए:',
    cancelBill: 'यह बिल रद्द कीजिए',
    cancelBillTitle: 'बिल रद्द करें?',
    cancelBillBody: 'यह बिल लिस्ट से हट जाएगा और इसके रिमाइंडर बंद हो जाएँगे। सिर्फ़ गलती से बना बिल ही रद्द कीजिए।',
    cancelBillDone: 'बिल रद्द हो गया।',
    cancelBillPaid: 'जिस बिल पर पेमेंट आ चुका है उसे रद्द नहीं कर सकते।',
    cancelled: 'रद्द',
    partial: 'आधा मिला',
    backupDueTitle: 'बैकअप का समय हो गया है',
    backupDueBody: 'बहुत दिनों से बैकअप नहीं हुआ। फ़ोन खो गया या खराब हुआ तो पूरा रजिस्टर चला जाएगा। अभी एक मिनट में बैकअप कर लीजिए।',
    remindTomorrow: 'कल याद दिलाइए',
    sendWithQr: 'QR के साथ भेजिए',
    sendWithoutQr: 'बिना QR के भेजिए',
    phoneHelp: 'यह नंबर मैसेज में "मोबाइल नंबर" के रूप में भी जाएगा — अभिभावक इस पर भी पे कर सकते हैं (अगर आपका UPI इसी नंबर से जुड़ा हो)।',
    messageLanguage: 'मैसेज की भाषा',
    messageLanguageHelp: 'रिमाइंडर और रसीद किस भाषा में जाएँ। किसी बच्चे के लिए अलग भाषा चुननी हो तो उसके फ़ॉर्म में बदल सकते हैं।',
    defaultOption: 'डिफ़ॉल्ट',
    backupSavedDownload: 'बैकअप फ़ाइल फ़ोन के Downloads में सेव हो गई। अब इसे Google Drive या WhatsApp पर भेज दीजिए।',
    sendingInNow: 'रिमाइंडर अभी इस भाषा में जा रहे हैं:',
    sendInEnglish: 'रिमाइंडर English में भेजिए',
    sendInHindi: 'रिमाइंडर हिंदी में भेजिए',
    sendingInChanged: 'अब रिमाइंडर इस भाषा में जाएँगे।',
    sendingInHelp: 'ऊपर का हिंदी | English बटन सिर्फ़ यह चुनता है कि आप कौन-सा मैसेज देख और बदल रहे हैं। भेजने की भाषा यहाँ या सेटिंग में बदलती है; किसी बच्चे के फ़ॉर्म में अलग भाषा चुनी हो तो उसके लिए वही चलेगी।',
    save: 'सेव कीजिए',
    close: 'बंद कीजिए',
    active: 'चालू',
    inactive: 'बंद',
    remove: 'हटाइए',
    advance: 'पहले से',
    dueTodayStage: 'आज देय',
    finalNotice: 'आख़िरी सूचना',
    required: 'यह भरना ज़रूरी है।',
    days: 'दिन',
    undoSend: 'भेजना वापस लीजिए',
    installHint: 'डेटा सुरक्षित रखने के लिए इस ऐप को होम स्क्रीन पर जोड़ लीजिए।',
    // More menu
    moreSubPickups: 'किराया सूची',
    moreSubImport: 'Excel / Google Sheets / CSV',
    moreSubInvoices: 'बाकी और पुराने बिल',
    moreSubTemplates: 'रिमाइंडर के शब्द · हिंदी / English',
    moreSubReports: 'वसूली और लेट वाले',
    moreSubBackup: 'सेव करना और वापस लाना',
    moreSubSettings: 'जानकारी, देय तारीख़, रिमाइंडर',
    // Pickup points
    noPickupsYet: 'अभी कोई पिकअप पॉइंट नहीं है।',
    noLandmark: 'पहचान नहीं दी',
    kmUnit: 'किमी',
    areaLandmark: 'इलाका / पहचान',
    monthlyFareLabel: 'महीने का किराया (₹) *',
    distanceKm: 'दूरी (किमी)',
    pointActiveLabel: 'चालू — नए बच्चों के लिए दिखेगा',
    pointInactiveLabel: 'बंद — नए बच्चों के लिए नहीं दिखेगा',
    pickupCannotDelete: 'यह पॉइंट हटाया नहीं जा सकता',
    pickupCannotDeleteBody: '{name} पर {count} बच्चे जुड़े हैं। इसे हटाने से उनका बिलिंग बिगड़ जाएगा।\n\nइसे "बंद" कर दीजिए — नए बच्चों के लिए नहीं दिखेगा और पुराना हिसाब सुरक्षित रहेगा।',
    markInactive: 'बंद कीजिए',
    pointNowInactive: '{name} अब बंद है।',
    removePointTitle: '{name} हटाएँ?',
    removePointBody: 'यहाँ कोई बच्चा नहीं जुड़ा है, इसलिए हटाना सुरक्षित है। यह वापस नहीं होगा।',
    yesRemove: 'हाँ, हटाइए',
    pointRemoved: '{name} हटा दिया।',
    // Student pages
    notEnrolled: 'फ़ीस सेट नहीं है',
    joined: 'जुड़ने की तारीख़',
    status: 'स्थिति',
    noInvoicesYet: 'अभी कोई बिल नहीं है।',
    noNotesYet: 'अभी कोई नोट नहीं है।',
    ledgerCopied: 'हिसाब कॉपी हो गया।'
  },
  en: {
    appName: 'Cab Fee Reminder',
    offline: 'Offline · all data on this phone',
    lock: 'Lock',
    lockHint: 'Enter your MPIN. The children’s data stays on this phone only.',
    lockFoot: 'Forgot the MPIN? Recovery is from your backup file — there is no server. Ten wrong tries mean a 60-second wait.',
    setupTitle: 'Let’s set up',
    setupHint: 'First, your details and a 4-digit MPIN. This MPIN will be asked every time you open the app.',
    yourName: 'Your name',
    businessName: 'Cab service name (optional)',
    yourPhone: 'Your phone number',
    setMpin: 'Set an MPIN (4 digits)',
    confirmMpin: 'Enter the MPIN again',
    mpinMismatch: 'The two MPINs do not match.',
    wrongMpin: 'Wrong MPIN.',
    finishSetup: 'Get started',
    dashboard: 'Today',
    remindersPending: 'Reminders to send',
    tapToSend: 'Tap to send',
    outstanding: 'Outstanding',
    overduePart: 'overdue',
    collected: 'Collected',
    thisMonth: 'This month',
    activeStudents: 'Active students',
    dueThisWeek: 'Due this week',
    generateInvoices: 'Check for new invoices',
    invoicesCreated: '{n} new invoice(s) created.',
    upToDate: 'Everything is already up to date.',
    backupStatus: 'Backup',
    backupNagAmber: 'days since the last backup. Take one soon.',
    backupNagRed: 'days since the last backup! Do it now.',
    backupNagFirst: 'No backup has been taken yet.',
    queue: 'Reminders',
    sendAll: 'Send all',
    send: 'Send',
    skip: 'Skip',
    undo: 'Undo',
    amount: 'Amount',
    sendingTo: 'Sending to',
    messagePreview: 'Message',
    openWhatsApp: 'Open WhatsApp',
    queueEmptyTitle: 'Every reminder is done.',
    queueEmptyBody: 'Nothing is waiting to be sent right now.',
    backToDash: 'Back to home',
    sentToday: 'Sent today',
    nPending: '{n} pending',
    quietHoursNote: 'Quiet hours are on (8pm–8am) — reminders will appear again in the morning.',
    students: 'Students',
    searchPlaceholder: 'Search name, school or number',
    noResults: 'Nothing matched.',
    addStudent: 'Add a student',
    all: 'All',
    overdue: 'Overdue',
    pending: 'Pending',
    paid: 'Paid',
    safetyCard: 'Safety card',
    bloodGroup: 'Blood group',
    bloodUnknown: 'Unknown',
    allergies: 'Allergies',
    emergency: 'Emergency',
    father: 'Father',
    mother: 'Mother',
    call: 'Call',
    record: 'Record',
    ledger: 'Ledger',
    notes: 'Notes',
    edit: 'Edit',
    enrolment: 'Fee setup',
    recordPayment: 'Record payment',
    share: 'Share',
    studentName: 'Student name',
    classLabel: 'Class',
    school: 'School',
    fatherName: 'Father’s name',
    fatherPhone: 'Father’s number',
    motherName: 'Mother’s name',
    motherPhone: 'Mother’s number',
    emergencyNumber: 'Emergency number',
    pickupPoint: 'Pickup point',
    allergyPlaceholder: 'e.g. peanuts, dust — inhaler in bag',
    cancel: 'Cancel',
    saveStudent: 'Save student',
    pickups: 'Pickup points',
    pickupIntro: 'Fares come from here. A point with students cannot be deleted — only marked inactive.',
    perMonth: 'per month',
    addPickup: 'Add a pickup point',
    fareLockNote: 'Changing a fare never re-prices past invoices — the fare is locked when the fee is set.',
    student: 'Student',
    feePlan: 'Fee plan',
    planMonthly: 'Monthly',
    planQuarterly: 'Quarterly',
    planYearly: 'Yearly',
    monthShort: 'mo',
    farePreview: 'Cycle amount',
    lockedFare: 'Locked fare',
    dueDay: 'Due day',
    firstInvoice: 'First invoice',
    lockExplain: 'This fare is locked in when the fee is saved. If the point’s fare changes later, this family’s past billing stays as it was.',
    saveEnrolment: 'Save fee',
    fareLockedToast: 'Fare locked at {fare} ✓',
    invoices: 'Invoices',
    outstandingTab: 'Outstanding',
    overdueTab: 'Overdue',
    paidTab: 'Paid',
    payment: 'Payment',
    settling: 'Settling',
    amountReceived: 'Amount received',
    mode: 'Mode',
    modeCash: 'Cash',
    modeUPI: 'UPI',
    modeBank: 'Bank transfer',
    modeCheque: 'Cheque',
    modeOther: 'Other',
    reference: 'Reference',
    refPlaceholder: 'UPI reference or cheque number',
    paidOn: 'Paid on',
    receiptNo: 'Receipt no.',
    receiptLabel: 'Receipt',
    savePayment: 'Save payment',
    paymentSaved: 'Payment recorded',
    invoiceSettled: 'Invoice settled and out of the queue.',
    balanceRemaining: 'Balance remaining: {amount}',
    partPaymentNote: 'Part payment — balance {amount} stays in the queue.',
    fullAmountNote: 'Full amount — the invoice will be settled.',
    dueOn: 'due {date}',
    receiptPreview: 'Receipt',
    shareReceipt: 'Send receipt on WhatsApp',
    done: 'Done',
    templates: 'Message templates',
    placeholders: 'Placeholders — tap to insert',
    livePreview: 'Live preview',
    unknownPlaceholder: 'Unrecognised placeholder {p} — this will not save.',
    saved: 'Saved ✓',
    backup: 'Backup & restore',
    lastBackup: 'Last backup',
    backupNow: 'Back up now',
    backupNever: 'Never',
    backupToday: 'Today',
    backupDaysAgo: '{n}d ago',
    backupExplain: 'A backup is one JSON file. Send it to Google Drive, email or your own WhatsApp. If the phone is lost, this file is the only thing that saves you.',
    restore: 'Restore',
    restoreExplain: 'A previous backup file rebuilds everything.',
    restoreTitle: 'Restore this backup?',
    restoreBody: 'Current: {cs} students, {ci} invoices.\nIncoming: {ns} students, {ni} invoices.\n\nEverything on the phone now will be replaced by this file. This cannot be undone.',
    yesRestore: 'Yes, restore',
    restored: 'Restored ✓',
    chooseFile: 'Choose a file',
    reports: 'Reports',
    billed: 'Billed',
    collectionRate: 'collected',
    byPickupPoint: 'By pickup point',
    point: 'Point',
    due: 'Due',
    defaulters: 'Over 30 days overdue',
    noneRightNow: 'None right now.',
    exportCsv: 'Export CSV',
    csvExported: 'CSV exported ✓',
    settings: 'Settings',
    languageSection: 'Language',
    operatorProfile: 'Your details',
    billing: 'Billing',
    defaultDueDay: 'Default due day',
    escalation: 'When reminders fire',
    quietHours: 'Quiet hours',
    quietNote: 'Queue only between 08:00 and 20:00',
    security: 'Security',
    lockNow: 'Lock now',
    mpinNote: 'MPIN is asked again after five minutes in the background.',
    more: 'More',
    home: 'Home',
    money: 'Money',
    paymentDetails: 'Payment details',
    upiId: 'Your UPI ID',
    upiHelp: 'Messages get a "Payment link" and your UPI ID. Opening the link shows the parent the amount, a copy-UPI-ID button and a QR. If left empty those lines are left out.',
    upiInvalid: 'That UPI ID does not look right (like name@bank). It was not saved.',
    testPayLink: 'Check the payment link (₹1)',
    paymentQr: 'Payment QR',
    uploadQr: 'Choose QR photo',
    changeQr: 'Change QR',
    qrSaved: 'QR saved ✓',
    attachQr: 'Send the QR with every reminder',
    qrHelp: 'Optional. The payment link is usually enough. With this on, WhatsApp opens its share list and you must pick the parent’s chat yourself, so it is slower.',
    qrPickChat: 'Pick the parent’s chat in WhatsApp',
    reminderTo: 'Send reminders to',
    reminderToHelp: 'One parent means half the taps. If they have no number, the other parent is used.',
    both: 'Both',
    feeDetails: 'Fee details',
    billFrom: 'Bill from',
    startToday: 'Today',
    startMonth: '1st of this month',
    startNext: 'Next month',
    thisMonthFee: 'This month’s fee',
    unpaid: 'Not paid yet',
    alreadyPaid: 'Already paid',
    oldDues: 'Old amount pending (₹)',
    oldDuesHelp: 'Anything still owed from earlier months. Leave empty if nothing.',
    saveAndNext: 'Save & add next',
    moreDetails: 'More details (can be added later)',
    quickHint: 'Only name, class, pickup point and one parent number are required.',
    addPickupFirst: 'Add a pickup point first (More → Pickup points).',
    importStudents: 'Import from Excel/CSV',
    importIntro: 'Add a whole list from Excel or Google Sheets at once. The first row must have column names.',
    chooseCsv: 'Choose CSV file',
    orPaste: 'Or copy from your sheet and paste here',
    downloadTemplate: 'Download a sample file',
    checkFile: 'Check',
    importNow: 'Import now',
    importDone: 'students added',
    readyToAdd: '{n} ready to add',
    alreadyInApp: '{n} already in the app (skipped)',
    haveProblems: '{n} have problems (skipped)',
    missingColumns: 'Missing column(s):',
    ignoredColumns: 'Ignored columns:',
    newPickupsCreated: 'New pickup points will be created:',
    andMore: '…and {n} more.',
    rowN: 'Row {n}',
    sendReminderNow: 'Send reminder now',
    sendReminderNowHelp: 'A message for today’s situation, without waiting for the schedule.',
    lockedWait: 'Too many wrong MPINs. Try again in',
    cancelBill: 'Cancel this bill',
    cancelBillTitle: 'Cancel this bill?',
    cancelBillBody: 'It will leave the lists and its reminders will stop. Only cancel a bill that was created by mistake.',
    cancelBillDone: 'Bill cancelled.',
    cancelBillPaid: 'A bill that already has a payment cannot be cancelled.',
    cancelled: 'Cancelled',
    partial: 'Part paid',
    backupDueTitle: 'Time for a backup',
    backupDueBody: 'There has been no backup for a long time. If the phone is lost or breaks, the whole register goes with it. Take one now — it takes a minute.',
    remindTomorrow: 'Remind me tomorrow',
    sendWithQr: 'Send with QR',
    sendWithoutQr: 'Send without QR',
    phoneHelp: 'This number also goes in the message as "Mobile number" — parents can pay to it too (if your UPI is linked to this number).',
    messageLanguage: 'Message language',
    messageLanguageHelp: 'The language reminders and receipts are sent in. You can set a different one for a particular student on their form.',
    defaultOption: 'Default',
    backupSavedDownload: 'Backup saved to your phone’s Downloads. Now send it to Google Drive or WhatsApp.',
    sendingInNow: 'Reminders are currently sent in:',
    sendInEnglish: 'Send reminders in English',
    sendInHindi: 'Send reminders in Hindi',
    sendingInChanged: 'Reminders will now go in this language.',
    sendingInHelp: 'The Hindi | English button above only chooses which message you are viewing and editing. The language that is sent is changed here or in Settings; a student with their own choice on their form keeps it.',
    save: 'Save',
    close: 'Close',
    active: 'Active',
    inactive: 'Inactive',
    remove: 'Remove',
    advance: 'Advance',
    dueTodayStage: 'Due today',
    finalNotice: 'Final notice',
    required: 'This field is required.',
    days: 'days',
    undoSend: 'Undo send',
    installHint: 'To keep your data safe, add this app to your home screen.',
    // More menu
    moreSubPickups: 'Fare master',
    moreSubImport: 'Excel / Google Sheets / CSV',
    moreSubInvoices: 'Outstanding and history',
    moreSubTemplates: 'Reminder wording · Hindi / English',
    moreSubReports: 'Collection, defaulters',
    moreSubBackup: 'Export / restore',
    moreSubSettings: 'Profile, due day, reminders',
    // Pickup points
    noPickupsYet: 'No pickup points yet.',
    noLandmark: 'No landmark',
    kmUnit: 'km',
    areaLandmark: 'Area / landmark',
    monthlyFareLabel: 'Monthly fare (₹) *',
    distanceKm: 'Distance (km)',
    pointActiveLabel: 'Active — offered on new students',
    pointInactiveLabel: 'Inactive — hidden from new students',
    pickupCannotDelete: 'This point cannot be deleted',
    pickupCannotDeleteBody: '{name} has {count} student(s) using it. Deleting it would break their billing.\n\nMark it inactive instead — it disappears for new students and all history stays intact.',
    markInactive: 'Mark inactive',
    pointNowInactive: '{name} is now inactive.',
    removePointTitle: 'Remove {name}?',
    removePointBody: 'No students use this point, so removing it is safe. This cannot be undone.',
    yesRemove: 'Yes, remove',
    pointRemoved: '{name} removed.',
    // Student pages
    notEnrolled: 'Fee not set up',
    joined: 'Joined',
    status: 'Status',
    noInvoicesYet: 'No invoices yet.',
    noNotesYet: 'No notes yet.',
    ledgerCopied: 'Ledger copied.'
  }
};

export function t(lang, key) {
  return (strings[lang] && strings[lang][key]) ?? (strings.en[key] ?? key);
}

/** Fills {name}-style placeholders, e.g. tf('hi', 'nPending', { n: 3 }). */
export function tf(lang, key, vars = {}) {
  return t(lang, key).replace(/\{(\w+)\}/g, (m, name) => (vars[name] !== undefined ? String(vars[name]) : m));
}

// Messages raised deep inside the app (validation, backup, billing) are written in English. In Hindi
// they are translated here, by exact text or by pattern, so a Hindi-speaking driver never gets a
// stray English sentence in a toast or under a field. Unknown messages pass through unchanged.
const ERRORS_HI = {
  'Nothing to undo — the previous state is no longer available.': 'वापस करने के लिए कुछ नहीं है — पुरानी स्थिति अब उपलब्ध नहीं है।',
  'Pickup point not found.': 'पिकअप पॉइंट नहीं मिला।',
  'Fee plan not found.': 'फ़ीस प्लान नहीं मिला।',
  'Invoice not found.': 'बिल नहीं मिला।',
  'A bill that already has a payment cannot be cancelled.': 'जिस बिल पर पेमेंट आ चुका है उसे रद्द नहीं कर सकते।',
  'Enter an amount greater than zero.': 'शून्य से ज़्यादा रकम डालिए।',
  'Payment not found.': 'पेमेंट नहीं मिला।',
  'Payments older than 30 days cannot be reversed here.': '30 दिन से पुराने पेमेंट यहाँ वापस नहीं हो सकते।',
  'A point name is required.': 'पॉइंट का नाम ज़रूरी है।',
  'Enter a fare in rupees.': 'किराया रुपये में डालिए।',
  'That name already exists.': 'यह नाम पहले से है।',
  'Name is required (2–60 characters).': 'नाम ज़रूरी है (2–60 अक्षर)।',
  'Class is required.': 'कक्षा ज़रूरी है।',
  '10 digits starting 6–9. At least one parent number is required.': '6–9 से शुरू होने वाले 10 अंक। कम से कम एक अभिभावक का नंबर ज़रूरी है।',
  '10 digits starting 6–9.': '6–9 से शुरू होने वाले 10 अंक।',
  'Choose a pickup point.': 'पिकअप पॉइंट चुनिए।',
  'This file is not a Cab Fee Reminder backup.': 'यह फ़ाइल Cab Fee Reminder की बैकअप फ़ाइल नहीं है।',
  'This backup was made by a newer version of the app and cannot be restored here.': 'यह बैकअप ऐप के नए वर्ज़न से बना है, यहाँ वापस नहीं लाया जा सकता।',
  'That file could not be read as an image.': 'यह फ़ाइल फोटो के रूप में नहीं पढ़ी जा सकी।',
  // import checks
  'Name is missing': 'नाम नहीं है',
  'Class is missing': 'कक्षा नहीं है',
  'Needs a valid 10-digit parent number': 'अभिभावक का सही 10 अंकों का नंबर चाहिए',
  'A parent number is not a valid 10-digit mobile': 'अभिभावक का एक नंबर सही 10 अंकों का मोबाइल नहीं है',
  'Pickup point is missing': 'पिकअप पॉइंट नहीं है',
  'Due day must be 1 to 28': 'देय तारीख़ 1 से 28 के बीच होनी चाहिए'
};

const ERROR_PATTERNS_HI = [
  [/^Unrecognised placeholder \{(.*)\} — this will not save\.$/, (m) => `यह प्लेसहोल्डर पहचाना नहीं गया: {${m[1]}} — सेव नहीं होगा।`],
  [/^Pickup point "(.*)" does not exist — add it, or give a fare in the file$/, (m) => `पिकअप पॉइंट "${m[1]}" ऐप में नहीं है — पहले जोड़िए, या फ़ाइल में किराया दीजिए`],
  [/^Plan "(.*)" is not monthly, quarterly or yearly$/, (m) => `प्लान "${m[1]}" महीना, तीन महीने या साल में से नहीं है`],
  [/^Language "(.*)" is not English or Hindi$/, (m) => `भाषा "${m[1]}" हिंदी या English नहीं है`]
];

export function localizeError(lang, message) {
  if (lang !== 'hi' || typeof message !== 'string') return message;
  if (ERRORS_HI[message]) return ERRORS_HI[message];
  for (const [pattern, build] of ERROR_PATTERNS_HI) {
    const m = message.match(pattern);
    if (m) return build(m);
  }
  return message;
}
