// 6.7: all interface labels in English and Hindi/Hinglish, switchable in settings.
export const strings = {
  hi: {
    appName: 'Cab Fee Reminder',
    offline: 'Offline · sab data phone par',
    lock: 'Lock',
    lockHint: 'MPIN daaliye. Bachchon ka data is phone par hi rehta hai.',
    lockFoot: 'MPIN bhool gaye? Backup file se recover hota hai — koi server nahi. 10 galat try par 60 second wait.',
    setupTitle: 'Shuru karte hain',
    setupHint: 'Pehle apni detail aur ek 4-digit MPIN set kar dijiye. Ye MPIN har baar app kholne par poochega.',
    yourName: 'Aapka naam',
    businessName: 'Cab service ka naam (optional)',
    yourPhone: 'Aapka number',
    setMpin: 'MPIN set kijiye (4 digit)',
    confirmMpin: 'MPIN dobara daaliye',
    mpinMismatch: 'Dono MPIN match nahi kar rahe.',
    wrongMpin: 'Galat MPIN.',
    finishSetup: 'Shuru kijiye',
    dashboard: 'Aaj ka hisaab',
    remindersPending: 'Reminder bhejne hain',
    tapToSend: 'Tap karke bhejiye',
    outstanding: 'Baaki paisa',
    overduePart: 'overdue',
    collected: 'Aaya',
    thisMonth: 'Is mahine',
    activeStudents: 'Active bachche',
    dueThisWeek: 'Is hafte due',
    generateInvoices: 'Naye invoice check kijiye',
    backupStatus: 'Backup',
    backupNagAmber: 'din se backup nahi hua. Kar lijiye.',
    backupNagRed: 'din se backup nahi hua! Abhi kar lijiye.',
    backupNagFirst: 'Abhi tak backup nahi hua.',
    queue: 'Reminder',
    sendAll: 'Sab bhejiye',
    send: 'Bhejiye',
    skip: 'Chhodiye',
    undo: 'Undo',
    amount: 'Amount',
    sendingTo: 'Kisko',
    messagePreview: 'Message',
    openWhatsApp: 'WhatsApp kholiye',
    queueEmptyTitle: 'Sab reminder ho gaye.',
    queueEmptyBody: 'Abhi koi reminder baaki nahi hai.',
    backToDash: 'Wapas home',
    sentToday: 'Aaj bheje gaye',
    quietHoursNote: 'Quiet hours chal rahe hain (raat 8 se subah 8) — reminder subah dikhenge.',
    students: 'Bachche',
    searchPlaceholder: 'Naam, school, number se dhundhiye',
    noResults: 'Kuch nahi mila.',
    addStudent: 'Naya bachcha jodiye',
    all: 'Sab',
    overdue: 'Overdue',
    pending: 'Baaki',
    paid: 'Ho gaya',
    safetyCard: 'Safety card',
    bloodGroup: 'Blood group',
    allergies: 'Allergy',
    emergency: 'Emergency',
    father: 'Papa',
    mother: 'Mummy',
    call: 'Call',
    record: 'Record',
    ledger: 'Hisaab',
    notes: 'Notes',
    edit: 'Badliye',
    enrolment: 'Enrolment',
    recordPayment: 'Payment likhiye',
    share: 'Share',
    studentName: 'Bachche ka naam',
    classLabel: 'Class',
    school: 'School',
    fatherName: 'Papa ka naam',
    fatherPhone: 'Papa ka number',
    motherName: 'Mummy ka naam',
    motherPhone: 'Mummy ka number',
    emergencyNumber: 'Emergency number',
    pickupPoint: 'Pickup point',
    allergyPlaceholder: 'Jaise: peanuts, dust — inhaler bag mein',
    cancel: 'Rehne dijiye',
    saveStudent: 'Save kijiye',
    pickups: 'Pickup point',
    pickupIntro: 'Fare yahin se aata hai. Bachchon wale point delete nahi honge — sirf inactive.',
    perMonth: 'per month',
    addPickup: 'Naya pickup point',
    fareLockNote: 'Fare badalne se purane invoice nahi badalte — enrolment par fare lock ho jaata hai.',
    student: 'Bachcha',
    feePlan: 'Fee plan',
    farePreview: 'Kitna banega',
    lockedFare: 'Locked fare',
    dueDay: 'Due day',
    firstInvoice: 'Pehla invoice',
    lockExplain: 'Ye fare enrolment ke saath lock ho jaayega. Baad mein point ka fare badla, to is family ka purana billing waise hi rahega.',
    saveEnrolment: 'Enrolment save kijiye',
    invoices: 'Invoice',
    outstandingTab: 'Baaki',
    overdueTab: 'Overdue',
    paidTab: 'Ho gaya',
    payment: 'Payment',
    settling: 'Kis invoice ka',
    amountReceived: 'Kitna mila',
    mode: 'Kaise mila',
    reference: 'Reference',
    refPlaceholder: 'UPI ref ya cheque number',
    paidOn: 'Date',
    receiptNo: 'Receipt',
    savePayment: 'Payment save kijiye',
    paymentSaved: 'Payment likh liya',
    receiptPreview: 'Receipt',
    shareReceipt: 'Receipt WhatsApp par bhejiye',
    done: 'Ho gaya',
    templates: 'Message',
    placeholders: 'Placeholder — tap karke daaliye',
    livePreview: 'Aisa dikhega',
    backup: 'Backup',
    lastBackup: 'Pichhla backup',
    backupNow: 'Abhi backup kijiye',
    backupExplain: 'Backup ek JSON file hai. Google Drive, email ya apne hi WhatsApp par bhej dijiye. Phone gum gaya to sirf yahi file bachaayegi.',
    restore: 'Restore',
    restoreExplain: 'Purani backup file se poora data wapas aa jaayega.',
    chooseFile: 'File chuniye',
    reports: 'Report',
    billed: 'Billed',
    collectionRate: 'collect ho gaya',
    byPickupPoint: 'Pickup point ke hisaab se',
    point: 'Point',
    due: 'Baaki',
    defaulters: '30 din se zyada purane',
    exportCsv: 'CSV export kijiye',
    settings: 'Setting',
    operatorProfile: 'Aapki detail',
    defaultDueDay: 'Har mahine due day',
    escalation: 'Reminder kab jaaye',
    quietHours: 'Raat mein band',
    quietNote: '8 baje subah se 8 baje raat tak hi',
    security: 'Suraksha',
    lockNow: 'Abhi lock kijiye',
    mpinNote: 'App 5 minute background mein rahe to MPIN dobara poochha jaayega.',
    more: 'Aur',
    home: 'Home',
    money: 'Paisa',
    paymentDetails: 'Payment ki detail',
    upiId: 'Aapka UPI ID',
    upiHelp: 'Message mein "Payment link" aur UPI ID jaayega. Link kholne par parent ko amount, UPI ID copy button aur QR dikhega. Khaali chhodne par ye lines nahi jaayengi.',
    upiInvalid: 'UPI ID galat lag raha hai (jaise naam@bank). Save nahi hua.',
    testPayLink: 'Payment link check kijiye (₹1)',
    paymentQr: 'Payment QR',
    uploadQr: 'QR photo chuniye',
    changeQr: 'QR badliye',
    attachQr: 'Har reminder ke saath QR bhejiye',
    qrHelp: 'Optional. Payment link kaafi hai. QR chalu karne par WhatsApp "share" list kholega aur parent ka chat aapko khud chunna hoga, isliye ye dheema hai.',
    qrPickChat: 'WhatsApp mein parent ka chat chuniye',
    reminderTo: 'Reminder kisko bhejna hai',
    reminderToHelp: 'Ek parent chuneinge to aadhe tap lagenge. Uska number na ho to doosre ko jaayega.',
    both: 'Dono',
    feeDetails: 'Fee ki detail',
    billFrom: 'Billing kab se',
    startToday: 'Aaj se',
    startMonth: 'Is mahine ki 1 se',
    startNext: 'Agle mahine se',
    thisMonthFee: 'Is mahine ki fee',
    unpaid: 'Baaki hai',
    alreadyPaid: 'De di hai',
    oldDues: 'Purana baaki (₹)',
    oldDuesHelp: 'Pichhle mahino ka jitna paisa baaki ho. Nahi hai to khaali chhodiye.',
    saveAndNext: 'Save karke agla jodiye',
    moreDetails: 'Aur detail (baad mein bhi bhar sakte hain)',
    quickHint: 'Sirf naam, class, pickup point aur ek parent ka number zaroori hai.',
    importStudents: 'Excel/CSV se jodiye',
    importIntro: 'Excel ya Google Sheet ki list ek saath daal dijiye. Pehli line mein column ke naam hone chahiye.',
    chooseCsv: 'CSV file chuniye',
    orPaste: 'Ya sheet se copy karke yahan paste kijiye',
    downloadTemplate: 'Namuna file download kijiye',
    checkFile: 'Check kijiye',
    importNow: 'Ab jodiye',
    importDone: 'bachche jud gaye',
    sendReminderNow: 'Reminder abhi bhejiye',
    sendReminderNowHelp: 'Due date ka intezaar kiye bina, aaj ke hisaab ka message.',
    lockedWait: 'Bahut baar galat MPIN. Ruk kar phir koshish kijiye:',
    cancelBill: 'Ye bill cancel kijiye',
    cancelBillTitle: 'Bill cancel karein?',
    cancelBillBody: 'Ye bill list se hat jaayega aur iske reminder band ho jaayenge. Galti se bana bill ho tabhi cancel kijiye.',
    cancelBillDone: 'Bill cancel ho gaya.',
    cancelBillPaid: 'Jis bill par payment aa chuka hai use cancel nahi kar sakte.',
    cancelled: 'Cancel',
    partial: 'Aadha mila',
    backupDueTitle: 'Backup ka waqt ho gaya hai',
    backupDueBody: 'Bahut din se backup nahi hua. Phone kho gaya ya kharab hua to poora register chala jaayega. Abhi ek minute mein backup kar lijiye.',
    remindTomorrow: 'Kal yaad dilaiye',
    sendWithQr: 'QR ke saath bhejiye',
    sendWithoutQr: 'Bina QR ke bhejiye',
    phoneHelp: 'Ye number message mein "Mobile number" ke roop mein bhi jaayega — parent isse bhi pay kar sakte hain (agar UPI isi number se juda ho).',
    save: 'Save kijiye',
    close: 'Band kijiye',
    active: 'Active',
    inactive: 'Inactive',
    remove: 'Hataiye',
    advance: 'Pehle se',
    dueTodayStage: 'Aaj due',
    finalNotice: 'Final notice',
    required: 'Ye bharna zaroori hai.',
    days: 'din',
    undoSend: 'Undo send',
    installHint: 'Data surakshit rakhne ke liye, is app ko home screen par add kar lijiye.'
  },
  en: {
    appName: 'Cab Fee Reminder',
    offline: 'Offline · all data on this phone',
    lock: 'Lock',
    lockHint: 'Enter your MPIN. The children’s data stays on this phone only.',
    lockFoot: 'Forgot the MPIN? Recovery is from your backup file — there is no server. Ten wrong tries mean a 60-second wait.',
    setupTitle: 'Let’s set up',
    setupHint: 'First, your details and a 4-digit MPIN. This MPIN will be asked every time you open the app.',
    yourName: 'Your name',
    businessName: 'Cab service name (optional)',
    yourPhone: 'Your phone number',
    setMpin: 'Set an MPIN (4 digits)',
    confirmMpin: 'Enter the MPIN again',
    mpinMismatch: 'The two MPINs do not match.',
    wrongMpin: 'Wrong MPIN.',
    finishSetup: 'Get started',
    dashboard: 'Today',
    remindersPending: 'Reminders to send',
    tapToSend: 'Tap to send',
    outstanding: 'Outstanding',
    overduePart: 'overdue',
    collected: 'Collected',
    thisMonth: 'This month',
    activeStudents: 'Active students',
    dueThisWeek: 'Due this week',
    generateInvoices: 'Check for new invoices',
    backupStatus: 'Backup',
    backupNagAmber: 'days since the last backup. Take one soon.',
    backupNagRed: 'days since the last backup! Do it now.',
    backupNagFirst: 'No backup has been taken yet.',
    queue: 'Reminders',
    sendAll: 'Send all',
    send: 'Send',
    skip: 'Skip',
    undo: 'Undo',
    amount: 'Amount',
    sendingTo: 'Sending to',
    messagePreview: 'Message',
    openWhatsApp: 'Open WhatsApp',
    queueEmptyTitle: 'Every reminder is done.',
    queueEmptyBody: 'Nothing is waiting to be sent right now.',
    backToDash: 'Back to home',
    sentToday: 'Sent today',
    quietHoursNote: 'Quiet hours are on (8pm–8am) — reminders will appear again in the morning.',
    students: 'Students',
    searchPlaceholder: 'Search name, school or number',
    noResults: 'Nothing matched.',
    addStudent: 'Add a student',
    all: 'All',
    overdue: 'Overdue',
    pending: 'Pending',
    paid: 'Paid',
    safetyCard: 'Safety card',
    bloodGroup: 'Blood group',
    allergies: 'Allergies',
    emergency: 'Emergency',
    father: 'Father',
    mother: 'Mother',
    call: 'Call',
    record: 'Record',
    ledger: 'Ledger',
    notes: 'Notes',
    edit: 'Edit',
    enrolment: 'Enrolment',
    recordPayment: 'Record payment',
    share: 'Share',
    studentName: 'Student name',
    classLabel: 'Class',
    school: 'School',
    fatherName: 'Father’s name',
    fatherPhone: 'Father’s number',
    motherName: 'Mother’s name',
    motherPhone: 'Mother’s number',
    emergencyNumber: 'Emergency number',
    pickupPoint: 'Pickup point',
    allergyPlaceholder: 'e.g. peanuts, dust — inhaler in bag',
    cancel: 'Cancel',
    saveStudent: 'Save student',
    pickups: 'Pickup points',
    pickupIntro: 'Fares come from here. A point with students cannot be deleted — only marked inactive.',
    perMonth: 'per month',
    addPickup: 'Add a pickup point',
    fareLockNote: 'Changing a fare never re-prices past invoices — the fare is locked at enrolment.',
    student: 'Student',
    feePlan: 'Fee plan',
    farePreview: 'Cycle amount',
    lockedFare: 'Locked fare',
    dueDay: 'Due day',
    firstInvoice: 'First invoice',
    lockExplain: 'This fare is locked into the enrolment. If the point’s fare changes later, this family’s past billing stays as it was.',
    saveEnrolment: 'Save enrolment',
    invoices: 'Invoices',
    outstandingTab: 'Outstanding',
    overdueTab: 'Overdue',
    paidTab: 'Paid',
    payment: 'Payment',
    settling: 'Settling',
    amountReceived: 'Amount received',
    mode: 'Mode',
    reference: 'Reference',
    refPlaceholder: 'UPI reference or cheque number',
    paidOn: 'Paid on',
    receiptNo: 'Receipt no.',
    savePayment: 'Save payment',
    paymentSaved: 'Payment recorded',
    receiptPreview: 'Receipt',
    shareReceipt: 'Send receipt on WhatsApp',
    done: 'Done',
    templates: 'Message templates',
    placeholders: 'Placeholders — tap to insert',
    livePreview: 'Live preview',
    backup: 'Backup & restore',
    lastBackup: 'Last backup',
    backupNow: 'Back up now',
    backupExplain: 'A backup is one JSON file. Send it to Google Drive, email or your own WhatsApp. If the phone is lost, this file is the only thing that saves you.',
    restore: 'Restore',
    restoreExplain: 'A previous backup file rebuilds everything.',
    chooseFile: 'Choose a file',
    reports: 'Reports',
    billed: 'Billed',
    collectionRate: 'collected',
    byPickupPoint: 'By pickup point',
    point: 'Point',
    due: 'Due',
    defaulters: 'Over 30 days overdue',
    exportCsv: 'Export CSV',
    settings: 'Settings',
    operatorProfile: 'Your details',
    defaultDueDay: 'Default due day',
    escalation: 'When reminders fire',
    quietHours: 'Quiet hours',
    quietNote: 'Queue only between 08:00 and 20:00',
    security: 'Security',
    lockNow: 'Lock now',
    mpinNote: 'MPIN is asked again after five minutes in the background.',
    more: 'More',
    home: 'Home',
    money: 'Money',
    paymentDetails: 'Payment details',
    upiId: 'Your UPI ID',
    upiHelp: 'Messages get a "Payment link" and your UPI ID. Opening the link shows the parent the amount, a copy-UPI-ID button and a QR. If left empty those lines are left out.',
    upiInvalid: 'That UPI ID does not look right (like name@bank). It was not saved.',
    testPayLink: 'Check the payment link (₹1)',
    paymentQr: 'Payment QR',
    uploadQr: 'Choose QR photo',
    changeQr: 'Change QR',
    attachQr: 'Send the QR with every reminder',
    qrHelp: 'Optional. The payment link is usually enough. With this on, WhatsApp opens its share list and you must pick the parent’s chat yourself, so it is slower.',
    qrPickChat: 'Pick the parent’s chat in WhatsApp',
    reminderTo: 'Send reminders to',
    reminderToHelp: 'One parent means half the taps. If they have no number, the other parent is used.',
    both: 'Both',
    feeDetails: 'Fee details',
    billFrom: 'Bill from',
    startToday: 'Today',
    startMonth: '1st of this month',
    startNext: 'Next month',
    thisMonthFee: 'This month’s fee',
    unpaid: 'Not paid yet',
    alreadyPaid: 'Already paid',
    oldDues: 'Old amount pending (₹)',
    oldDuesHelp: 'Anything still owed from earlier months. Leave empty if nothing.',
    saveAndNext: 'Save & add next',
    moreDetails: 'More details (can be added later)',
    quickHint: 'Only name, class, pickup point and one parent number are required.',
    importStudents: 'Import from Excel/CSV',
    importIntro: 'Add a whole list from Excel or Google Sheets at once. The first row must have column names.',
    chooseCsv: 'Choose CSV file',
    orPaste: 'Or copy from your sheet and paste here',
    downloadTemplate: 'Download a sample file',
    checkFile: 'Check',
    importNow: 'Import now',
    importDone: 'students added',
    sendReminderNow: 'Send reminder now',
    sendReminderNowHelp: 'A message for today’s situation, without waiting for the schedule.',
    lockedWait: 'Too many wrong MPINs. Try again in',
    cancelBill: 'Cancel this bill',
    cancelBillTitle: 'Cancel this bill?',
    cancelBillBody: 'It will leave the lists and its reminders will stop. Only cancel a bill that was created by mistake.',
    cancelBillDone: 'Bill cancelled.',
    cancelBillPaid: 'A bill that already has a payment cannot be cancelled.',
    cancelled: 'Cancelled',
    partial: 'Part paid',
    backupDueTitle: 'Time for a backup',
    backupDueBody: 'There has been no backup for a long time. If the phone is lost or breaks, the whole register goes with it. Take one now — it takes a minute.',
    remindTomorrow: 'Remind me tomorrow',
    sendWithQr: 'Send with QR',
    sendWithoutQr: 'Send without QR',
    phoneHelp: 'This number also goes in the message as "Mobile number" — parents can pay to it too (if your UPI is linked to this number).',
    save: 'Save',
    close: 'Close',
    active: 'Active',
    inactive: 'Inactive',
    remove: 'Remove',
    advance: 'Advance',
    dueTodayStage: 'Due today',
    finalNotice: 'Final notice',
    required: 'This field is required.',
    days: 'days',
    undoSend: 'Undo send',
    installHint: 'To keep your data safe, add this app to your home screen.'
  }
};

export function t(lang, key) {
  return (strings[lang] && strings[lang][key]) ?? (strings.en[key] ?? key);
}
